### ISSUE TITLE
False negatives from CompletelyPositiveQ

### ISSUE THREAD

**Issue by cgranade** [QuantumUtils/quantum-utils-mathematica#6]
For some completely positive channels, it seems that `CompletelyPositiveQ` fails to correctly return `True`. In particular, for a qubit amplitude damping channel, `CompletelyPositiveQ` returns `False` if the strength is left as a symbol, even if enough `$Assumptions` are provided such that `FullSimplify` and `Reduce` give that all eigenvalues are nonnegative.

```
In[1]:= Needs["QuantumChannel`"]

In[2]:= $Assumptions = And[
   $Assumptions,
   1 >= p >= 0
   ];

In[3]:= AmplitudeDampingChannel[p_] = FullSimplify@Super@Kraus[{( {
       {1, 0},
       {0, Sqrt[1 - p]}
      } ), ( {
       {0, Sqrt[p]},
       {0, 0}
      } )}]

Out[3]= "Super"[{{1, 0, 0, p}, {0, Sqrt[1 - p], 0, 0}, {0, 0, Sqrt[
   1 - p], 0}, {0, 0, 0, 1 - p}}, "<params>"]

In[4]:= AmplitudeDampingChannel[0] // CompletelyPositiveQ

Out[4]= True

In[5]:= AmplitudeDampingChannel[1] // CompletelyPositiveQ

Out[5]= True

In[6]:= choieigs = 
 Choi[AmplitudeDampingChannel[p]] // FullSimplify // First // 
  Eigenvalues

Out[6]= {0, 0, 2 - p, p}

In[7]:= Simplify[Reduce[choieigs >= 0]]

Out[7]= True

In[8]:= CompletelyPositiveQ[AmplitudeDampingChannel[p], 
 Simplify -> FullSimplify]

Out[8]= False

In[9]:= CompletelyPositiveQ[AmplitudeDampingChannel[1]]

Out[9]= True
```

It appears that the problem goes back to the builtin function `PositiveSemidefiniteMatrixQ`:

```
In[10]:= PositiveSemidefiniteMatrixQ[
 First@Choi@AmplitudeDampingChannel[p]]

Out[10]= False

In[11]:= AllQ[# >= 0 &, 
 Eigenvalues[First@Choi@AmplitudeDampingChannel[p]]]

Out[11]= 2 - p >= 0 && p >= 0

In[12]:= Simplify[%]

Out[12]= True
```

**Comment by ihincks** [comment]
I looked through the documentation for PositiveSemidefiniteMatrixQ, including scope and possible issues, and it seems like there is no (documented) way to make it think that symbols are anything but complex. We might have to revert to a manual method. I have asked on this SE question:

http://mathematica.stackexchange.com/questions/80002/checking-if-a-symbolic-matrix-is-positive-semi-definite

**Comment by chriseclectic** [comment]
It should work correctly with assumptions now. I set it to use `PositiveSemidefiniteMatrixQ` for numeric channels, and to manually check non-negativity of eigenvalues, using `FullSimplify` with any given assumptions, for non-numeric channels. It will now return an error if it can't deduce the non-negativity of any eigenvalues with the given assumptions:

```
In[1]:= Needs["QuantumChannel`"]

In[2]:= $Assumptions = And[
   $Assumptions,
   1 >= p >= 0
   ];

In[3]:= AmplitudeDampingChannel[p_] = FullSimplify@Super@Kraus[{( {
       {1, 0},
       {0, Sqrt[1 - p]}
      } ), ( {
       {0, Sqrt[p]},
       {0, 0}
      } )}];

In[4]:= CompletelyPositiveQ[AmplitudeDampingChannel[k]]

CompletelyPositiveQ::assum: Cannot deduce nonnegativity of eigenvalues {2-k,k} with given assumptions.

In[5]:= CompletelyPositiveQ[AmplitudeDampingChannel[p]]

Out[5]:=True
```

Of course using `Eigenvalues` and `FullSimplify` might make it very slow, or not finish evaluating, for complicated channels.
