### ISSUE TITLE
CGate returns Null for empty controls.

### ISSUE THREAD

**Issue by cgranade** [QuantumUtils/quantum-utils-mathematica#9]
Using `CGate` with an empty list for the controls argument returns `Null`, as in the following example:

``` mathematica
In[2]:= CGate[{2, 2}, TP@X, 1, {}] // FullForm
Out[2]//FullForm= Null
```

I think that this should either return an uncontrolled gate acting on the target register, or should produce a message and an unevaluated result.

**Comment by cgranade** [comment]
Perhaps relatedly, `CGate` also propagates a `Null` if the control dimension is 1:

``` mathematica
In[3]:= CGate[{2, 1}, TP@X, 1, 2]

Out[3]= {{1 + {{0, 1}, {1, 0}}\[CircleTimes]KroneckerProduct[Null, 
     Conjugate[Null]], {{0, 1}, {1, 0}}\[CircleTimes]KroneckerProduct[
    Null, Conjugate[Null]]}, {{{0, 1}, {1, 
     0}}\[CircleTimes]KroneckerProduct[Null, Conjugate[Null]], 
  1 + {{0, 1}, {1, 0}}\[CircleTimes]KroneckerProduct[Null, 
     Conjugate[Null]]}}
```

Here, the problem is that the `Control → 1` option doesn't make sense for a 1-dimensional space, but that error isn't properly being caught and turned into a message. This can be verified by noting that the following snippet does what is expected:

``` mathematica
In[4]:= CGate[{2, 2, 1}, TP@X, 2, 3, Control -> 0]

Out[4]= {{0, 1, 0, 0}, {1, 0, 0, 0}, {0, 0, 0, 1}, {0, 0, 1, 0}}
```

**Comment by ihincks** [comment]
I agree this is a bug. Of your suggestions, I like the uncontrolled gate solution best.

**Comment by chriseclectic** [comment]
Fixed.

The first case was a bug with the  3-argument function being called with the wrong inputs due to {} being interpreted as an empty set of options.

For the second case I added an error message if a control subsystem is 1-dimensional.
